### ISSUE TITLE
key de Place en Guías y Puntos de Interés.

### ISSUE THREAD

**Issue by ivan-jgr** [visitantesmcd/visitantes-android#2]
El modelo para las guías es este:

![image](https://user-images.githubusercontent.com/13913074/114353913-ce7a8600-9b2a-11eb-8d9d-35df2ecb6300.png)

y el modelo para los puntos de interés es este:

![image](https://user-images.githubusercontent.com/13913074/114353991-e3efb000-9b2a-11eb-9caf-175aa7d4c035.png)

¿Por qué necesitamos el key del place en los dos? ¿No basta con tenerlo sólo en las guías? porque todo punto de interés pertence a una guía.

**Comment by carlossiguina** [comment]
Creo que era por si necesitabamos una vista donde se mostrarán Guías o Puntos de Interés por separado y no desde la vista de un Sitio.

Entonces se mostraba su información y algún botón para visitar el lugar al que pertenece. Pero se puede obviar si en un futuro se puede modificar sin ningún problema.

**Comment by carlossiguina** [comment]
Lo tome en cuenta de una vez, por si era dificil modificar igual como pasaba en Django.

**Comment by ivan-jgr** [comment]
@carlossiguina 
Ya escribí el esquema para que lo revisemos el miércoles.
Un par de cambios de los que no estoy seguro:
1. La relación entre categorías y lugares es many-to-many
2. La relación entre multimedia y lugares es many-to-one
3. La relacion entre reseñas y lugares es many-to-one
4. La relación entre puntos de interés y lugares es many-to-one
5. La relación entre puntos de interés y guías es many-to-one

Diseñe las guías para que un lugar tenga muchos puntos de interés (el id del lugar está en puntos de interés) y para que una guía tenga muchos puntos de interés (el id de la guía está en el punto de interés). **La guía ya no tiene el id del lugar** porque una guía puede contener puntos de interés que son de lugares diferentes ¿?

**Comment by carlossiguina** [comment]
Simon.
Yo estoy haciendo diseño pero debo pasarlos a esta app de acá para verlos el miércoles también.

Respecto a las guías, según entiendo no. Una guía solo tendrá puntos de interés de un mismo sitio y no más. Lo que significa que entre guias y lugares es many-to-one y entre puntos y guías es many-to-many porque puede repetirse puntos de interés en otras guías.

Las otras relaciones que hiciste las veo bastante bien
