### ISSUE TITLE
Idioma al momento del Desarrollo.

### ISSUE THREAD

**Issue by carlossiguina** [visitantesmcd/visitantes-android#3]
Por la imagen del issue anterior, veo que escribiste tanto el objeto como sus atributos en ingles.

Entonces, todo los objetos, clases, layouts, fragments, activities, etc., lo vamos a escribir en inglés también cierto?

En el caso de los textos dentro de la aplicación (no de los objetos prueba en la base de datos) utilizamos el español como idioma principal y el inglés y el resto que soliciten como secundarios?

**Comment by ivan-jgr** [comment]
Sí, creo que si acordamos eso de escribir los campos en inglés para no mezclarlos como en la base de datos que tenemos en Firebase.

Yo creo que si es mejor que usemos *todo* en inglés como idioma base tanto los objetos, clases, layouts, etc. y también usar como principal el inglés en los textos.
